# Generated by Django 5.0 on 2025-07-17 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('workout_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workout_group')),
            ],
        ),
    ]
