# Generated by Django 5.0 on 2025-07-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workout_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=100)),
                ('uom', models.CharField(choices=[('kg', 'Kilograms'), ('bars', 'Bars')], max_length=10)),
                ('max_weight', models.IntegerField()),
                ('workout_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workout_group')),
            ],
        ),
    ]
