# Generated by Django 5.0 on 2025-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='max_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='uom',
            field=models.CharField(choices=[('kg', 'Kg'), ('bars', 'Bars')], max_length=10),
        ),
    ]
