# Generated by Django 5.0 on 2025-08-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_exercise_max_weight_alter_exercise_uom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exercise',
        ),
    ]
