# Generated by Django 5.0 on 2025-08-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=100)),
                ('workout_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workout_group')),
            ],
        ),
    ]
