# Generated by Django 5.0 on 2025-08-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_best',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(choices=[('kg', 'Kg'), ('bars', 'Bars')], max_length=10)),
                ('max_weight', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exercise')),
            ],
        ),
    ]
